DRUG_REFERENCE = {
    "Metformin": "Biguanide",
    "Glipizide": "Sulfonylurea",
    "Glyburide": "Sulfonylurea",
    "Glimepiride": "Sulfonylurea",
    "Sitagliptin": "DPP-4 inhibitor",
    "Saxagliptin": "DPP-4 inhibitor",
    "Empagliflozin": "SGLT-2 inhibitor",
    "Dapagliflozin": "SGLT-2 inhibitor",
    "Canagliflozin": "SGLT-2 inhibitor",
    "Semaglutide": "GLP-1 receptor agonist",
    "Liraglutide": "GLP-1 receptor agonist",
    "Dulaglutide": "GLP-1 receptor agonist",
    "Tirzepatide": "GIP/GLP-1 receptor agonist",
    "Pioglitazone": "Thiazolidinedione",
    "Insulin glargine": "Basal insulin",
    "Insulin lispro": "Rapid-acting insulin",
    "Insulin aspart": "Rapid-acting insulin",
    "NPH insulin": "Intermediate-acting insulin",
}